# Generated by Django 4.2.5 on 2024-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scrape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offender_age_number_0_9",
                    models.IntegerField(verbose_name="加害者(0歳〜9歳)"),
                ),
                (
                    "offender_age_number_10_19",
                    models.IntegerField(verbose_name="加害者(10歳〜19歳)"),
                ),
                (
                    "offender_age_number_20_29",
                    models.IntegerField(verbose_name="加害者(20歳〜29歳)"),
                ),
                (
                    "offender_age_number_30_39",
                    models.IntegerField(verbose_name="加害者(30歳〜39歳)"),
                ),
                (
                    "offender_age_number_40_49",
                    models.IntegerField(verbose_name="加害者(40歳〜49歳)"),
                ),
                (
                    "offender_age_number_50_59",
                    models.IntegerField(verbose_name="加害者(50歳〜59歳)"),
                ),
                (
                    "offender_age_number_60_69",
                    models.IntegerField(verbose_name="加害者(60歳〜69歳)"),
                ),
                (
                    "offender_age_number_70_79",
                    models.IntegerField(verbose_name="加害者(70歳〜79歳)"),
                ),
                (
                    "offender_age_number_80_89",
                    models.IntegerField(verbose_name="加害者(80歳〜89歳)"),
                ),
                (
                    "offender_age_90_older",
                    models.IntegerField(verbose_name="加害者(90歳~)"),
                ),
                ("unknown", models.IntegerField(verbose_name="加害者(90歳~)")),
                ("offender_sum_total", models.IntegerField(verbose_name="加害者の全世代の総数")),
                (
                    "victim_age_number_10_19",
                    models.IntegerField(verbose_name="加害者(10歳~19歳)"),
                ),
                (
                    "victim_age_number_20_29",
                    models.IntegerField(verbose_name="加害者(20歳~29歳)"),
                ),
                (
                    "victim_age_number_30_39",
                    models.IntegerField(verbose_name="加害者(30歳~39歳)"),
                ),
                (
                    "victim_age_number_40_49",
                    models.IntegerField(verbose_name="加害者(40歳~49歳)"),
                ),
                (
                    "victim_age_number_50_59",
                    models.IntegerField(verbose_name="加害者(50歳~59歳)"),
                ),
                ("victim_sum_total", models.IntegerField(verbose_name="被害者の全世代の総数")),
                (
                    "personal_weapons",
                    models.IntegerField(verbose_name="身体を使った攻撃(手、足など)"),
                ),
                ("handgun", models.IntegerField(verbose_name="ハンドガン")),
                ("knife_cutting_instrument", models.IntegerField(verbose_name="鋭利な凶器")),
                ("firearm", models.IntegerField(verbose_name="火器")),
                ("none", models.IntegerField(verbose_name="none")),
            ],
        ),
    ]
