# Generated by Django 4.2.5 on 2024-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrape",
            name="type_of_weapons_sum_total",
            field=models.IntegerField(default=1, verbose_name="反抗に用いた武器の総数"),
            preserve_default=False,
        ),
    ]
